### ISSUE TITLE
Error message description can be improved in UpdateRecordRespPars

### ISSUE THREAD

**Issue by siddeshas** [eclipse/keyple#10]
Error message for SW 0x6B00 is just P2 value not supported. Could you please give provide more description regarding the error.

**Comment by jeanpierrefortune** [comment]
Sorry for the delay.
For better tracking of this kind of problem, please place this kind of issue in the repository associated with the code concerned.

"P2 value not supported" is the explanation given by the card specification in the case where the status word is 6B00.
Its interpretation should not be the responsibility of the application developer.

Feel free to reopen an issue in https://github.com/eclipse/keyple-card-calypso-java-lib  if you wish.
