### ISSUE TITLE
C++ Distributed module extension

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse/keyple#15]
Hello team,
Currently the distributed mode is not supported for C++ and I don't see it in the [roadmap](https://keyple.org/community/roadmap/).
Is there any plan for this feature or not?
Regards,

**Comment by pterr** [comment]
Hello, we are currently working to update Keyple's existing C++ components to the same functional level as Keyple's Java components (already based on the Keypop APIs). → we expect it to be available by June 2024.
Once this stage will have been completed, it will be easier to provide additional features to the Keyple's C++ implementation.

Regarding the distributed mode, we think it would be useful to port to C++ at least the Keyple components needed to integrate a "Keyple C++ client" with a "Keyple Java server".
