### ISSUE TITLE
Add a "CHANGELOG.md" file to each repository

### ISSUE THREAD

**Issue by andrei-cristea** [eclipse/keyple#6]
The presence of the file "CHANGELOG.md" is part of the good development practices to make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.

It is recommended that the content of the file follows the format standardized by [keepachangelog.com](https://keepachangelog.com/en/1.0.0/).

**Comment by Misshunter1** [comment]
unblock and unlink keep alive   "State"` 
[misshunter1](hh1.com)
